// frontend/etms-frontend/src/app/shared/sidebar/sidebar.component.ts
import { Component, signal, computed } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { NgIf, NgFor } from '@angular/common';
import { AuthService } from '../../core/services/auth.service';

interface NavItem {
  label: string; icon: string; route: string;
  roles?: string[]; badge?: string;
}

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, NgIf, NgFor],
  templateUrl: './sidebar.component.html',
  styleUrl: './sidebar.component.scss'
})
export class SidebarComponent {
  collapsed = signal(false);

  navItems: NavItem[] = [
    { label: 'Dashboard',    icon: '⬡', route: '/dashboard' },
    { label: 'Tasks',        icon: '✦', route: '/tasks' },
    { label: 'Employees',    icon: '◎', route: '/employees', roles: ['Admin','Manager'] },
    { label: 'Attendance',   icon: '◷', route: '/attendance' },
    { label: 'Leave',        icon: '◈', route: '/leave' },
    { label: 'Performance',  icon: '◆', route: '/performance' },
    { label: 'My Profile',   icon: '◉', route: '/profile' },
  ];

  constructor(public auth: AuthService) {}

  visibleItems = computed(() =>
    this.navItems.filter(item =>
      !item.roles || item.roles.includes(this.auth.role)
    )
  );

  toggle() { this.collapsed.update(v => !v); }

  get initials(): string {
    const u = this.auth.currentUser();
    if (!u) return '?';
    const parts = u.email.split('@')[0].split('.');
    return parts.map((p: string) => p[0]?.toUpperCase() ?? '').join('').slice(0, 2);
  }

  get avatarColor(): string {
    const colors = ['avatar-blue','avatar-teal','avatar-violet','avatar-rose','avatar-amber','avatar-sky'];
    return colors[this.auth.userEmail?.charCodeAt(0) % colors.length];
  }
  get email(): string { return this.auth.userEmail; }
  get role(): string  { return this.auth.role; }
}

<aside class="sidebar" [class.collapsed]="collapsed()">

  <!-- Logo / Brand -->
  <div class="sidebar-brand">
    <div class="brand-icon">
      <span>ET</span>
    </div>
    <div class="brand-text" *ngIf="!collapsed()">
      <span class="brand-name">ETMS</span>
      <span class="brand-tagline">Task Management</span>
    </div>
    <button class="collapse-btn" (click)="toggle()" [title]="collapsed() ? 'Expand' : 'Collapse'">
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path *ngIf="!collapsed()" d="m15 18-6-6 6-6"/>
        <path *ngIf="collapsed()"  d="m9 18 6-6-6-6"/>
      </svg>
    </button>
  </div>

  <!-- Nav -->
  <nav class="sidebar-nav">
    <div class="nav-section-label" *ngIf="!collapsed()">MENU</div>

    <a *ngFor="let item of visibleItems()"
       [routerLink]="item.route"
       routerLinkActive="active"
       class="nav-item"
       [title]="collapsed() ? item.label : ''">
      <span class="nav-icon">{{ item.icon }}</span>
      <span class="nav-label" *ngIf="!collapsed()">{{ item.label }}</span>
      <span class="nav-badge" *ngIf="item.badge && !collapsed()">{{ item.badge }}</span>
    </a>
  </nav>

  <!-- User section -->
  <div class="sidebar-footer">
    <div class="user-card" [class.compact]="collapsed()">
      <div class="avatar avatar-md {{ avatarColor }}">{{ initials }}</div>
      <div class="user-info" *ngIf="!collapsed()">
        <span class="user-email">{{ email }}</span>
        <span class="user-role-badge">{{ role }}</span>
      </div>
    </div>
    <button class="logout-btn" (click)="auth.logout()" [title]="collapsed() ? 'Logout' : ''">
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/>
        <polyline points="16 17 21 12 16 7"/>
        <line x1="21" y1="12" x2="9" y2="12"/>
      </svg>
      <span *ngIf="!collapsed()">Logout</span>
    </button>
  </div>

</aside>

// frontend/etms-react/src/components/Layout/Sidebar.js
import React, { useState } from 'react';
import { NavLink, useNavigate } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';
import { avatarColor } from '../../services/api';

const NAV_ITEMS = [
  { label: 'Dashboard',   icon: '⬡', route: '/dashboard' },
  { label: 'Tasks',       icon: '✦', route: '/tasks' },
  { label: 'Employees',   icon: '◎', route: '/employees', managerOnly: true },
  { label: 'Attendance',  icon: '◷', route: '/attendance' },
  { label: 'Leave',       icon: '◈', route: '/leave' },
  { label: 'Performance', icon: '◆', route: '/performance' },
  { label: 'My Profile',  icon: '◉', route: '/profile' },
];

export default function Sidebar({ collapsed, onToggle }) {
  const { user, isManager, logout } = useAuth();
  const navigate = useNavigate();

  const visibleItems = NAV_ITEMS.filter((item) => !item.managerOnly || isManager);

  const email = user?.email || '';
  const role  = user?.role  || '';
  const emailInitials = email
    .split('@')[0]
    .split('.')
    .map((p) => p[0]?.toUpperCase() || '')
    .join('')
    .slice(0, 2);

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  return (
    <aside className={`sidebar${collapsed ? ' collapsed' : ''}`}>
      {/* Brand */}
      <div className="sidebar-brand">
        <div className="brand-icon">ET</div>
        {!collapsed && (
          <div className="brand-text">
            <span className="brand-name">ETMS</span>
            <span className="brand-tagline">Task Management</span>
          </div>
        )}
        <button className="collapse-btn" onClick={onToggle} title={collapsed ? 'Expand' : 'Collapse'}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            {collapsed
              ? <path d="m9 18 6-6-6-6" />
              : <path d="m15 18-6-6 6-6" />}
          </svg>
        </button>
      </div>

      {/* Nav */}
      <nav className="sidebar-nav">
        {!collapsed && <div className="nav-section-label">MENU</div>}
        {visibleItems.map((item) => (
          <NavLink
            key={item.route}
            to={item.route}
            className={({ isActive }) => `nav-item${isActive ? ' active' : ''}`}
            title={collapsed ? item.label : undefined}
          >
            <span className="nav-icon">{item.icon}</span>
            {!collapsed && <span className="nav-label">{item.label}</span>}
          </NavLink>
        ))}
      </nav>

      {/* Footer */}
      <div className="sidebar-footer">
        <div className={`user-card${collapsed ? ' compact' : ''}`}>
          <div className={`avatar avatar-md ${avatarColor(email)}`}>{emailInitials}</div>
          {!collapsed && (
            <div className="user-info">
              <span className="user-email">{email}</span>
              <span className="user-role-badge">{role}</span>
            </div>
          )}
        </div>
        <button className="logout-btn" onClick={handleLogout} title={collapsed ? 'Logout' : undefined}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
            <polyline points="16 17 21 12 16 7" />
            <line x1="21" y1="12" x2="9" y2="12" />
          </svg>
          {!collapsed && <span>Logout</span>}
        </button>
      </div>
    </aside>
  );
}
