// frontend/etms-react/src/Pages/Performance.jsx
import React, { useEffect, useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../contexts/ToastContext';
import { taskService, lookupService } from '../services/api';

const MONTHS = Array.from({ length: 12 }, (_, i) => i + 1);
const YEARS  = Array.from({ length: 5  }, (_, i) => new Date().getFullYear() - i);

function scoreColor(score) {
  if (score >= 4) return 'var(--success)';
  if (score >= 3) return 'var(--warning)';
  return 'var(--danger)';
}

function StarRow({ score }) {
  return (
    <div className="perf-stars">
      {Array(5).fill(0).map((_, i) => (
        <span key={i} className={`star${i < Math.round(score) ? ' filled' : ''}`}>★</span>
      ))}
    </div>
  );
}

export default function Performance() {
  const { isManager } = useAuth();
  const toast = useToast();

  const [summaries,  setSummaries]  = useState([]);
  const [users,      setUsers]      = useState([]);
  const [loading,    setLoading]    = useState(true);
  const [publishing, setPublishing] = useState(false);
  const [preview,    setPreview]    = useState(null);

  const [pForm, setPForm] = useState({
    employeeUserId: '', year: new Date().getFullYear(),
    month: '', managerComment: '',
  });

  useEffect(() => {
    taskService.getMyPerformance().then((r) => { setSummaries(r.data); setLoading(false); }).catch(() => setLoading(false));
    if (isManager) lookupService.getUsers().then((r) => setUsers(r.data)).catch(() => {});
  }, [isManager]);

  const previewPerformance = async () => {
    if (!pForm.employeeUserId) { toast.show('Select an employee.', 'error'); return; }
    try {
      const res = await taskService.previewPerformance({ ...pForm, month: pForm.month || null });
      setPreview(res.data);
    } catch { toast.show('Preview failed.', 'error'); }
  };

  const publish = async () => {
    if (!preview) { toast.show('Preview first.', 'warning'); return; }
    setPublishing(true);
    try {
      await taskService.publishPerformance({ ...pForm, month: pForm.month || null });
      toast.show('Performance published!', 'success');
      setPreview(null);
      const res = await taskService.getMyPerformance();
      setSummaries(res.data);
    } catch (e) { toast.show(e.response?.data?.message || 'Publish failed.', 'error'); }
    finally { setPublishing(false); }
  };

  return (
    <>
      <div className="page-header">
        <div>
          <h1 className="page-title">Performance</h1>
          <p className="page-subtitle">Track and publish employee performance reviews.</p>
        </div>
      </div>

      {/* Manager: Publish Panel */}
      {isManager && (
        <div className="card publish-card">
          <div className="card-header"><h3 className="card-title">Publish Performance Review</h3></div>
          <div className="card-body">
            <div className="publish-grid">
              <div className="form-group">
                <label className="form-label">Employee *</label>
                <select className="form-control" value={pForm.employeeUserId} onChange={(e) => setPForm({ ...pForm, employeeUserId: e.target.value })}>
                  <option value="">Select employee...</option>
                  {users.map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}
                </select>
              </div>
              <div className="form-group">
                <label className="form-label">Year</label>
                <select className="form-control" value={pForm.year} onChange={(e) => setPForm({ ...pForm, year: +e.target.value })}>
                  {YEARS.map((y) => <option key={y} value={y}>{y}</option>)}
                </select>
              </div>
              <div className="form-group">
                <label className="form-label">Month (optional)</label>
                <select className="form-control" value={pForm.month} onChange={(e) => setPForm({ ...pForm, month: e.target.value })}>
                  <option value="">All year</option>
                  {MONTHS.map((m) => <option key={m} value={m}>Month {m}</option>)}
                </select>
              </div>
            </div>
            <div className="form-group">
              <label className="form-label">Manager Comment</label>
              <textarea className="form-control" rows={3} placeholder="Add a comment for the employee..." value={pForm.managerComment} onChange={(e) => setPForm({ ...pForm, managerComment: e.target.value })} />
            </div>

            {preview && (
              <div className="preview-box">
                <div className="preview-stat">
                  <span className="preview-num" style={{ color: scoreColor(preview.averageScore) }}>{preview.averageScore?.toFixed(1)}</span>
                  <span className="preview-label">Average Score (out of 5)</span>
                </div>
                <div className="preview-stat">
                  <span className="preview-num">{preview.taskCount}</span>
                  <span className="preview-label">Reviewed Tasks</span>
                </div>
                <div className="stars-preview">
                  {Array(5).fill(0).map((_, i) => (
                    <span key={i} className={`star${i < Math.round(preview.averageScore) ? ' filled' : ''}`}>★</span>
                  ))}
                </div>
              </div>
            )}

            <div className="publish-actions">
              <button className="btn btn-secondary" onClick={previewPerformance}>Preview</button>
              <button className="btn btn-primary" onClick={publish} disabled={publishing || !preview}>
                {publishing ? <span className="spinner" /> : 'Publish Review'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Performance History */}
      <div className="card" style={{ marginTop: isManager ? 24 : 0 }}>
        <div className="card-header"><h3 className="card-title">My Performance History</h3></div>
        {loading && (
          <div className="loading-rows">
            {[1,2].map((i) => <div key={i} className="skeleton" style={{ height: 80, margin: '4px 0' }} />)}
          </div>
        )}
        {!loading && summaries.length === 0 && (
          <div className="empty-state"><div className="empty-icon">◆</div><h4>No performance reviews yet</h4><p>Your published performance reviews will appear here.</p></div>
        )}
        {!loading && summaries.length > 0 && (
          <div className="performance-list">
            {summaries.map((s) => (
              <div className="perf-item" key={s.id}>
                <div className="perf-left">
                  <div className="score-ring" style={{ '--score-color': scoreColor(s.averageScore) }}>
                    <span className="score-value">{s.averageScore?.toFixed(1)}</span>
                    <span className="score-max">/5</span>
                  </div>
                </div>
                <div className="perf-body">
                  <div className="perf-period">
                    {s.year}{s.month ? ` · Month ${s.month}` : ''}{s.week ? ` · Week ${s.week}` : ''}
                  </div>
                  <StarRow score={s.averageScore} />
                  {s.managerComment && <div className="perf-comment">{s.managerComment}</div>}
                </div>
                <div className="perf-right">
                  <span className="perf-date text-muted text-sm">
                    {s.createdAt ? new Date(s.createdAt).toLocaleDateString('en-US', { year:'numeric', month:'short', day:'numeric' }) : '—'}
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </>
  );
}

// frontend/etms-frontend/src/app/features/performance/performance.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { NgIf, NgFor, DatePipe, DecimalPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TaskService, LookupService, ToastService } from '../../core/services/api.service';
import { AuthService } from '../../core/services/auth.service';
import { PerformanceSummary, UserOption } from '../../core/models/models';

@Component({
  selector: 'app-performance',
  standalone: true,
  imports: [NgIf, NgFor, FormsModule, DatePipe, DecimalPipe],
  templateUrl: './performance.component.html',
  styleUrl: './performance.component.scss'
})
export class PerformanceComponent implements OnInit {
  summaries  = signal<PerformanceSummary[]>([]);
  users      = signal<UserOption[]>([]);
  loading    = signal(true);
  publishing = signal(false);
  preview    = signal<{ averageScore: number; taskCount: number } | null>(null);

  publishForm = { employeeUserId: '', year: new Date().getFullYear(), month: null as number|null, week: null as number|null, managerComment: '' };
  years = Array.from({ length: 5 }, (_, i) => new Date().getFullYear() - i);

  constructor(public auth: AuthService, private taskSvc: TaskService, private lookup: LookupService, private toast: ToastService) {}

  ngOnInit() {
    this.taskSvc.getMyPerformance().subscribe({ next: s => { this.summaries.set(s); this.loading.set(false); }, error: () => this.loading.set(false) });
    if (this.auth.isManager) this.lookup.getUsers().subscribe({ next: u => this.users.set(u) });
  }

  previewPerformance() {
    if (!this.publishForm.employeeUserId) { this.toast.show('Select an employee.', 'error'); return; }
    this.taskSvc.previewPerformance(this.publishForm).subscribe({ next: r => this.preview.set(r), error: () => this.toast.show('Preview failed.', 'error') });
  }

  publish() {
    if (!this.preview()) { this.toast.show('Preview first.', 'warning'); return; }
    this.publishing.set(true);
    this.taskSvc.publishPerformance(this.publishForm).subscribe({
      next: () => { this.publishing.set(false); this.preview.set(null); this.toast.show('Performance published!', 'success'); this.taskSvc.getMyPerformance().subscribe({ next: s => this.summaries.set(s) }); },
      error: (e) => { this.publishing.set(false); this.toast.show(e.error?.message || 'Publish failed.', 'error'); }
    });
  }

  scoreColor(score: number): string {
    if (score >= 4) return 'var(--success)';
    if (score >= 3) return 'var(--warning)';
    return 'var(--danger)';
  }

  starArray = (n: number) => Array(5).fill(0).map((_,i) => i < Math.round(n));
}

<div class="page-header">
  <div>
    <h1 class="page-title">Performance</h1>
    <p class="page-subtitle">Track and publish employee performance reviews.</p>
  </div>
</div>

<!-- Manager: Publish Panel -->
<div class="card publish-card" *ngIf="auth.isManager">
  <div class="card-header">
    <h3 class="card-title">Publish Performance Review</h3>
  </div>
  <div class="card-body">
    <div class="publish-grid">
      <div class="form-group">
        <label class="form-label">Employee *</label>
        <select class="form-control" [(ngModel)]="publishForm.employeeUserId">
          <option value="">Select employee...</option>
          <option *ngFor="let u of users()" [value]="u.id">{{ u.name }}</option>
        </select>
      </div>
      <div class="form-group">
        <label class="form-label">Year</label>
        <select class="form-control" [(ngModel)]="publishForm.year">
          <option *ngFor="let y of years" [value]="y">{{ y }}</option>
        </select>
      </div>
      <div class="form-group">
        <label class="form-label">Month (optional)</label>
        <select class="form-control" [(ngModel)]="publishForm.month">
          <option [value]="null">All year</option>
          <option *ngFor="let m of [1,2,3,4,5,6,7,8,9,10,11,12]" [value]="m">Month {{ m }}</option>
        </select>
      </div>
    </div>
    <div class="form-group">
      <label class="form-label">Manager Comment</label>
      <textarea class="form-control" rows="3" placeholder="Add a comment for the employee..."
                [(ngModel)]="publishForm.managerComment"></textarea>
    </div>

    <div class="preview-box" *ngIf="preview()">
      <div class="preview-stat">
        <span class="preview-num" [style.color]="scoreColor(preview()!.averageScore)">
          {{ preview()!.averageScore | number:'1.1-1' }}
        </span>
        <span class="preview-label">Average Score (out of 5)</span>
      </div>
      <div class="preview-stat">
        <span class="preview-num">{{ preview()!.taskCount }}</span>
        <span class="preview-label">Reviewed Tasks</span>
      </div>
      <div class="stars-preview">
        <span *ngFor="let f of starArray(preview()!.averageScore)" class="star" [class.filled]="f">★</span>
      </div>
    </div>

    <div class="publish-actions">
      <button class="btn btn-secondary" (click)="previewPerformance()">Preview</button>
      <button class="btn btn-primary" (click)="publish()" [disabled]="publishing() || !preview()">
        <span class="spinner" *ngIf="publishing()"></span>
        <span *ngIf="!publishing()">Publish Review</span>
      </button>
    </div>
  </div>
</div>

<!-- My Performance Summaries -->
<div class="card" [style.margin-top]="auth.isManager ? '24px' : '0'">
  <div class="card-header">
    <h3 class="card-title">My Performance History</h3>
  </div>

  <div *ngIf="loading()" style="padding:16px;display:flex;flex-direction:column;gap:6px">
    <div class="skeleton" style="height:80px" *ngFor="let i of [1,2]"></div>
  </div>

  <div *ngIf="!loading() && summaries().length === 0" class="empty-state">
    <div class="empty-icon">◆</div>
    <h4>No performance reviews yet</h4>
    <p>Your published performance reviews will appear here.</p>
  </div>

  <div class="performance-list" *ngIf="!loading() && summaries().length > 0">
    <div class="perf-item" *ngFor="let s of summaries()">
      <div class="perf-left">
        <div class="score-ring" [style.--score-color]="scoreColor(s.averageScore)">
          <span class="score-value">{{ s.averageScore | number:'1.1-1' }}</span>
          <span class="score-max">/5</span>
        </div>
      </div>
      <div class="perf-body">
        <div class="perf-period">
          {{ s.year }}
          <span *ngIf="s.month">· Month {{ s.month }}</span>
          <span *ngIf="s.week">· Week {{ s.week }}</span>
        </div>
        <div class="perf-stars">
          <span *ngFor="let f of starArray(s.averageScore)" class="star" [class.filled]="f">★</span>
        </div>
        <div class="perf-comment" *ngIf="s.managerComment">{{ s.managerComment }}</div>
      </div>
      <div class="perf-right">
        <span class="perf-date text-muted text-sm">{{ s.createdAt | date:'mediumDate' }}</span>
      </div>
    </div>
  </div>
</div>
