// frontend/etms-react/src/Pages/Login.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../contexts/ToastContext';

const ROLES = [
  { id: 1, name: 'Admin' },
  { id: 2, name: 'Manager' },
  { id: 3, name: 'Employee' },
];
const DEPARTMENTS = [
  { id: 1, name: 'IT' },
  { id: 2, name: 'HR' },
  { id: 3, name: 'Finance' },
];

export default function Login() {
  const navigate = useNavigate();
  const { login, register } = useAuth();
  const toast = useToast();

  const [mode, setMode] = useState('login');
  const [loading, setLoading] = useState(false);
  const [showPass, setShowPass] = useState(false);
  const [error, setError] = useState('');

  const [loginForm, setLoginForm] = useState({ email: '', password: '' });
  const [regForm, setRegForm] = useState({
    firstName: '', lastName: '', email: '', password: '',
    roleId: 3, departmentId: 1,
  });

  const handleLogin = async (e) => {
    e.preventDefault();
    if (!loginForm.email || !loginForm.password) { setError('Please enter your email and password.'); return; }
    setLoading(true); setError('');
    try {
      await login(loginForm.email, loginForm.password);
      navigate('/dashboard');
    } catch (err) {
      setError(err.response?.data?.message || err.response?.data || 'Invalid credentials. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleRegister = async (e) => {
    e.preventDefault();
    const { firstName, lastName, email, password } = regForm;
    if (!firstName || !lastName || !email || !password) { setError('All fields are required.'); return; }
    setLoading(true); setError('');
    try {
      const selectedRole = ROLES.find((r) => r.id === +regForm.roleId);
      const selectedDept = DEPARTMENTS.find((d) => d.id === +regForm.departmentId);
      await register({
        ...regForm,
        roleId: +regForm.roleId, role: selectedRole?.name ?? 'Employee',
        departmentId: +regForm.departmentId, department: selectedDept?.name ?? 'IT',
      });
      toast.show('Account created! Please log in.', 'success');
      setMode('login');
    } catch (err) {
      setError(err.response?.data || 'Registration failed. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-page">
      {/* Left hero */}
      <div className="login-hero">
        <div className="hero-content">
          <div className="hero-logo">ET</div>
          <h1>Employee Task<br />Management System</h1>
          <p>Streamline your workforce. Track tasks, manage attendance, and monitor performance — all in one place.</p>
          <div className="hero-features">
            <div className="feature-item"><span className="feature-icon">✦</span><span>Real-time task tracking</span></div>
            <div className="feature-item"><span className="feature-icon">◷</span><span>Attendance &amp; leave management</span></div>
            <div className="feature-item"><span className="feature-icon">◆</span><span>Performance analytics</span></div>
          </div>
          <div className="hero-dots"><span /><span /><span /></div>
        </div>
      </div>

      {/* Right form panel */}
      <div className="login-form-panel">
        <div className="form-container">
          <div className="auth-tabs">
            <button className={`tab-btn${mode === 'login' ? ' active' : ''}`} onClick={() => { setMode('login'); setError(''); }}>Sign In</button>
            <button className={`tab-btn${mode === 'register' ? ' active' : ''}`} onClick={() => { setMode('register'); setError(''); }}>Create Account</button>
          </div>

          {error && <div className="error-banner"><span>⚠</span> {error}</div>}

          {mode === 'login' ? (
            <form onSubmit={handleLogin}>
              <div className="form-group">
                <label className="form-label">Email Address</label>
                <div className="input-icon-wrap">
                  <svg className="input-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <rect x="2" y="4" width="20" height="16" rx="2" /><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
                  </svg>
                  <input type="email" className="form-control" placeholder="you@company.com"
                    value={loginForm.email} onChange={(e) => setLoginForm({ ...loginForm, email: e.target.value })} required />
                </div>
              </div>
              <div className="form-group">
                <label className="form-label">Password</label>
                <div className="input-icon-wrap">
                  <svg className="input-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <rect x="3" y="11" width="18" height="11" rx="2" /><path d="M7 11V7a5 5 0 0 1 10 0v4" />
                  </svg>
                  <input type={showPass ? 'text' : 'password'} className="form-control"
                    placeholder="Enter your password"
                    value={loginForm.password} onChange={(e) => setLoginForm({ ...loginForm, password: e.target.value })} required />
                  <button type="button" className="toggle-pass" onClick={() => setShowPass((v) => !v)}>
                    {showPass ? '🙈' : '👁'}
                  </button>
                </div>
              </div>
              <button type="submit" className="btn btn-primary btn-lg submit-btn" disabled={loading}>
                {loading ? <span className="spinner" /> : 'Sign In'}
              </button>
            </form>
          ) : (
            <form onSubmit={handleRegister}>
              <div className="form-row">
                <div className="form-group">
                  <label className="form-label">First Name</label>
                  <input type="text" className="form-control" placeholder="John"
                    value={regForm.firstName} onChange={(e) => setRegForm({ ...regForm, firstName: e.target.value })} required />
                </div>
                <div className="form-group">
                  <label className="form-label">Last Name</label>
                  <input type="text" className="form-control" placeholder="Doe"
                    value={regForm.lastName} onChange={(e) => setRegForm({ ...regForm, lastName: e.target.value })} required />
                </div>
              </div>
              <div className="form-group">
                <label className="form-label">Email Address</label>
                <input type="email" className="form-control" placeholder="you@company.com"
                  value={regForm.email} onChange={(e) => setRegForm({ ...regForm, email: e.target.value })} required />
              </div>
              <div className="form-group">
                <label className="form-label">Password</label>
                <input type="password" className="form-control" placeholder="Create a strong password"
                  value={regForm.password} onChange={(e) => setRegForm({ ...regForm, password: e.target.value })} required />
              </div>
              <div className="form-row">
                <div className="form-group">
                  <label className="form-label">Role</label>
                  <select className="form-control" value={regForm.roleId} onChange={(e) => setRegForm({ ...regForm, roleId: +e.target.value })}>
                    {ROLES.map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}
                  </select>
                </div>
                <div className="form-group">
                  <label className="form-label">Department</label>
                  <select className="form-control" value={regForm.departmentId} onChange={(e) => setRegForm({ ...regForm, departmentId: +e.target.value })}>
                    {DEPARTMENTS.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}
                  </select>
                </div>
              </div>
              <button type="submit" className="btn btn-primary btn-lg submit-btn" disabled={loading}>
                {loading ? <span className="spinner" /> : 'Create Account'}
              </button>
            </form>
          )}
        </div>
      </div>
    </div>
  );
}

// frontend/etms-frontend/src/app/features/auth/login/login.component.ts
import { Component, signal } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { NgIf, NgFor } from '@angular/common';
import { AuthService } from '../../../core/services/auth.service';
import { ToastService } from '../../../core/services/api.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [FormsModule, NgIf, NgFor],
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss'
})
export class LoginComponent {
  mode: 'login' | 'register' = 'login';
  loading = signal(false);
  showPass = signal(false);
  error = signal('');

  // Login form
  loginForm = { email: '', password: '' };

  // Register form
  registerForm = {
    firstName: '', lastName: '', email: '', password: '',
    roleId: 3, role: 'Employee', departmentId: 1, department: 'IT'
  };

  roles = [
    { id: 1, name: 'Admin' }, { id: 2, name: 'Manager' }, { id: 3, name: 'Employee' }
  ];
  departments = [
    { id: 1, name: 'IT' }, { id: 2, name: 'HR' }, { id: 3, name: 'Finance' }
  ];

  constructor(private auth: AuthService, private router: Router, private toast: ToastService) {}

  onLogin() {
    if (!this.loginForm.email || !this.loginForm.password) {
      this.error.set('Please enter your email and password.');
      return;
    }
    this.loading.set(true);
    this.error.set('');
    this.auth.login(this.loginForm).subscribe({
      next: () => { this.loading.set(false); this.router.navigate(['/dashboard']); },
      error: (err) => {
        this.loading.set(false);
        this.error.set(err.error?.message || err.error || 'Invalid credentials. Please try again.');
      }
    });
  }

  onRegister() {
    const f = this.registerForm;
    if (!f.firstName || !f.lastName || !f.email || !f.password) {
      this.error.set('All fields are required.'); return;
    }
    const selectedRole = this.roles.find(r => r.id === +f.roleId);
    const selectedDept = this.departments.find(d => d.id === +f.departmentId);
    this.loading.set(true);
    this.error.set('');
    this.auth.register({
      ...f,
      roleId: +f.roleId, role: selectedRole?.name ?? 'Employee',
      departmentId: +f.departmentId, department: selectedDept?.name ?? 'IT'
    }).subscribe({
      next: () => {
        this.loading.set(false);
        this.toast.show('Account created! Please log in.', 'success');
        this.mode = 'login';
      },
      error: (err) => {
        this.loading.set(false);
        this.error.set(err.error || 'Registration failed. Please try again.');
      }
    });
  }

  togglePassword() {
  this.showPass.update(v => !v);
}
  switchMode(m: 'login' | 'register') { this.mode = m; this.error.set(''); }
}

<div class="login-page">

  <!-- Left panel – decorative -->
  <div class="login-hero">
    <div class="hero-content">
      <div class="hero-logo">
        <span>ET</span>
      </div>
      <h1>Employee Task<br>Management System</h1>
      <p>Streamline your workforce. Track tasks, manage attendance, and monitor performance — all in one place.</p>

      <div class="hero-features">
        <div class="feature-item">
          <span class="feature-icon">✦</span>
          <span>Real-time task tracking</span>
        </div>
        <div class="feature-item">
          <span class="feature-icon">◷</span>
          <span>Attendance & leave management</span>
        </div>
        <div class="feature-item">
          <span class="feature-icon">◆</span>
          <span>Performance analytics</span>
        </div>
      </div>

      <div class="hero-dots">
        <span></span><span></span><span></span>
      </div>
    </div>
  </div>

  <!-- Right panel – form -->
  <div class="login-form-panel">
    <div class="form-container">

      <!-- Tabs -->
      <div class="auth-tabs">
        <button class="tab-btn" [class.active]="mode === 'login'"
                (click)="switchMode('login')">Sign In</button>
        <button class="tab-btn" [class.active]="mode === 'register'"
                (click)="switchMode('register')">Create Account</button>
      </div>

      <!-- Error -->
      <div class="error-banner" *ngIf="error()">
        <span>⚠</span> {{ error() }}
      </div>

      <!-- Login Form -->
      <form *ngIf="mode === 'login'" (ngSubmit)="onLogin()" #loginFormRef="ngForm">
        <div class="form-group">
          <label class="form-label">Email Address</label>
          <div class="input-icon-wrap">
            <svg class="input-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <rect x="2" y="4" width="20" height="16" rx="2"/>
              <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/>
            </svg>
            <input type="email" class="form-control" placeholder="you@company.com"
                   [(ngModel)]="loginForm.email" name="email" required autocomplete="email" />
          </div>
        </div>

        <div class="form-group">
          <label class="form-label">Password</label>
          <div class="input-icon-wrap">
            <svg class="input-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <rect x="3" y="11" width="18" height="11" rx="2" ry="2"/>
              <path d="M7 11V7a5 5 0 0 1 10 0v4"/>
            </svg>
            <input [type]="showPass() ? 'text' : 'password'" class="form-control"
                   placeholder="Enter your password"
                   [(ngModel)]="loginForm.password" name="password" required autocomplete="current-password" />
            <button type="button" class="toggle-pass" (click)="togglePassword()">
              {{ showPass() ? '🙈' : '👁' }}
            </button>
          </div>
        </div>

        <button type="submit" class="btn btn-primary btn-lg submit-btn" [disabled]="loading()">
          <span class="spinner" *ngIf="loading()"></span>
          <span *ngIf="!loading()">Sign In</span>
        </button>
      </form>

      <!-- Register Form -->
      <form *ngIf="mode === 'register'" (ngSubmit)="onRegister()">
        <div class="form-row">
          <div class="form-group">
            <label class="form-label">First Name</label>
            <input type="text" class="form-control" placeholder="John"
                   [(ngModel)]="registerForm.firstName" name="firstName" required />
          </div>
          <div class="form-group">
            <label class="form-label">Last Name</label>
            <input type="text" class="form-control" placeholder="Doe"
                   [(ngModel)]="registerForm.lastName" name="lastName" required />
          </div>
        </div>

        <div class="form-group">
          <label class="form-label">Email Address</label>
          <input type="email" class="form-control" placeholder="you@company.com"
                 [(ngModel)]="registerForm.email" name="email" required />
        </div>

        <div class="form-group">
          <label class="form-label">Password</label>
          <input type="password" class="form-control" placeholder="Create a strong password"
                 [(ngModel)]="registerForm.password" name="password" required />
        </div>

        <div class="form-row">
          <div class="form-group">
            <label class="form-label">Role</label>
            <select class="form-control" [(ngModel)]="registerForm.roleId" name="roleId">
              <option *ngFor="let r of roles" [value]="r.id">{{ r.name }}</option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-label">Department</label>
            <select class="form-control" [(ngModel)]="registerForm.departmentId" name="departmentId">
              <option *ngFor="let d of departments" [value]="d.id">{{ d.name }}</option>
            </select>
          </div>
        </div>

        <button type="submit" class="btn btn-primary btn-lg submit-btn" [disabled]="loading()">
          <span class="spinner" *ngIf="loading()"></span>
          <span *ngIf="!loading()">Create Account</span>
        </button>
      </form>

    </div>
  </div>

</div>
